export const initialCountryList = [
	'US',
	'Canada',
	'United Kingdom',
	'China',
	'Netherlands',
	'Australia',
	'Denmark',
	'France',
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua and Barbuda',
	'Argentina',
	'Armenia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burma',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Central African Republic',
	'Chad',
	'Chile',
	'Colombia',
	'Congo (Brazzaville)',
	'Congo (Kinshasa)',
	'Costa Rica',
	"Cote d'Ivoire",
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czechia',
	'Diamond Princess',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Holy See',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Korea, South',
	'Kosovo',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'MS Zaandam',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Namibia',
	'Nepal',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Vincent and the Grenadines',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Somalia',
	'South Africa',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan*',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'Uruguay',
	'Uzbekistan',
	'Venezuela',
	'Vietnam',
	'West Bank and Gaza',
	'Western Sahara',
	'Zambia',
	'Zimbabwe',
]

export const initialCountryStateList = [
	{ Province_State: 'Alabama', Country_Region: 'US' },
	{ Province_State: 'Alaska', Country_Region: 'US' },
	{ Province_State: 'Alberta', Country_Region: 'Canada' },
	{ Province_State: 'Anguilla', Country_Region: 'United Kingdom' },
	{ Province_State: 'Anhui', Country_Region: 'China' },
	{ Province_State: 'Arizona', Country_Region: 'US' },
	{ Province_State: 'Arkansas', Country_Region: 'US' },
	{ Province_State: 'Aruba', Country_Region: 'Netherlands' },
	{
		Province_State: 'Australian Capital Territory',
		Country_Region: 'Australia',
	},
	{ Province_State: 'Beijing', Country_Region: 'China' },
	{ Province_State: 'Bermuda', Country_Region: 'United Kingdom' },
	{
		Province_State: 'Bonaire, Sint Eustatius and Saba',
		Country_Region: 'Netherlands',
	},
	{ Province_State: 'British Columbia', Country_Region: 'Canada' },
	{
		Province_State: 'British Virgin Islands',
		Country_Region: 'United Kingdom',
	},
	{ Province_State: 'California', Country_Region: 'US' },
	{ Province_State: 'Cayman Islands', Country_Region: 'United Kingdom' },
	{ Province_State: 'Channel Islands', Country_Region: 'United Kingdom' },
	{ Province_State: 'Chongqing', Country_Region: 'China' },
	{ Province_State: 'Colorado', Country_Region: 'US' },
	{ Province_State: 'Connecticut', Country_Region: 'US' },
	{ Province_State: 'Curacao', Country_Region: 'Netherlands' },
	{ Province_State: 'Delaware', Country_Region: 'US' },
	{ Province_State: 'Diamond Princess', Country_Region: 'Canada' },
	{ Province_State: 'Diamond Princess', Country_Region: 'US' },
	{ Province_State: 'District of Columbia', Country_Region: 'US' },
	{
		Province_State: 'Falkland Islands (Malvinas)',
		Country_Region: 'United Kingdom',
	},
	{ Province_State: 'Faroe Islands', Country_Region: 'Denmark' },
	{ Province_State: 'Florida', Country_Region: 'US' },
	{ Province_State: 'French Guiana', Country_Region: 'France' },
	{ Province_State: 'French Polynesia', Country_Region: 'France' },
	{ Province_State: 'Fujian', Country_Region: 'China' },
	{ Province_State: 'Gansu', Country_Region: 'China' },
	{ Province_State: 'Georgia', Country_Region: 'US' },
	{ Province_State: 'Gibraltar', Country_Region: 'United Kingdom' },
	{ Province_State: 'Grand Princess', Country_Region: 'Canada' },
	{ Province_State: 'Grand Princess', Country_Region: 'US' },
	{ Province_State: 'Greenland', Country_Region: 'Denmark' },
	{ Province_State: 'Guadeloupe', Country_Region: 'France' },
	{ Province_State: 'Guam', Country_Region: 'US' },
	{ Province_State: 'Guangdong', Country_Region: 'China' },
	{ Province_State: 'Guangxi', Country_Region: 'China' },
	{ Province_State: 'Guizhou', Country_Region: 'China' },
	{ Province_State: 'Hainan', Country_Region: 'China' },
	{ Province_State: 'Hawaii', Country_Region: 'US' },
	{ Province_State: 'Hebei', Country_Region: 'China' },
	{ Province_State: 'Heilongjiang', Country_Region: 'China' },
	{ Province_State: 'Henan', Country_Region: 'China' },
	{ Province_State: 'Hong Kong', Country_Region: 'China' },
	{ Province_State: 'Hubei', Country_Region: 'China' },
	{ Province_State: 'Hunan', Country_Region: 'China' },
	{ Province_State: 'Idaho', Country_Region: 'US' },
	{ Province_State: 'Illinois', Country_Region: 'US' },
	{ Province_State: 'Indiana', Country_Region: 'US' },
	{ Province_State: 'Inner Mongolia', Country_Region: 'China' },
	{ Province_State: 'Iowa', Country_Region: 'US' },
	{ Province_State: 'Isle of Man', Country_Region: 'United Kingdom' },
	{ Province_State: 'Jiangsu', Country_Region: 'China' },
	{ Province_State: 'Jiangxi', Country_Region: 'China' },
	{ Province_State: 'Jilin', Country_Region: 'China' },
	{ Province_State: 'Kansas', Country_Region: 'US' },
	{ Province_State: 'Kentucky', Country_Region: 'US' },
	{ Province_State: 'Liaoning', Country_Region: 'China' },
	{ Province_State: 'Louisiana', Country_Region: 'US' },
	{ Province_State: 'Macau', Country_Region: 'China' },
	{ Province_State: 'Maine', Country_Region: 'US' },
	{ Province_State: 'Manitoba', Country_Region: 'Canada' },
	{ Province_State: 'Martinique', Country_Region: 'France' },
	{ Province_State: 'Maryland', Country_Region: 'US' },
	{ Province_State: 'Massachusetts', Country_Region: 'US' },
	{ Province_State: 'Mayotte', Country_Region: 'France' },
	{ Province_State: 'Michigan', Country_Region: 'US' },
	{ Province_State: 'Minnesota', Country_Region: 'US' },
	{ Province_State: 'Mississippi', Country_Region: 'US' },
	{ Province_State: 'Missouri', Country_Region: 'US' },
	{ Province_State: 'Montana', Country_Region: 'US' },
	{ Province_State: 'Montserrat', Country_Region: 'United Kingdom' },
	{ Province_State: 'N/A', Country_Region: 'Afghanistan' },
	{ Province_State: 'N/A', Country_Region: 'Albania' },
	{ Province_State: 'N/A', Country_Region: 'Algeria' },
	{ Province_State: 'N/A', Country_Region: 'Andorra' },
	{ Province_State: 'N/A', Country_Region: 'Angola' },
	{ Province_State: 'N/A', Country_Region: 'Antigua and Barbuda' },
	{ Province_State: 'N/A', Country_Region: 'Argentina' },
	{ Province_State: 'N/A', Country_Region: 'Armenia' },
	{ Province_State: 'N/A', Country_Region: 'Austria' },
	{ Province_State: 'N/A', Country_Region: 'Azerbaijan' },
	{ Province_State: 'N/A', Country_Region: 'Bahamas' },
	{ Province_State: 'N/A', Country_Region: 'Bahrain' },
	{ Province_State: 'N/A', Country_Region: 'Bangladesh' },
	{ Province_State: 'N/A', Country_Region: 'Barbados' },
	{ Province_State: 'N/A', Country_Region: 'Belarus' },
	{ Province_State: 'N/A', Country_Region: 'Belgium' },
	{ Province_State: 'N/A', Country_Region: 'Belize' },
	{ Province_State: 'N/A', Country_Region: 'Benin' },
	{ Province_State: 'N/A', Country_Region: 'Bhutan' },
	{ Province_State: 'N/A', Country_Region: 'Bolivia' },
	{ Province_State: 'N/A', Country_Region: 'Bosnia and Herzegovina' },
	{ Province_State: 'N/A', Country_Region: 'Botswana' },
	{ Province_State: 'N/A', Country_Region: 'Brazil' },
	{ Province_State: 'N/A', Country_Region: 'Brunei' },
	{ Province_State: 'N/A', Country_Region: 'Bulgaria' },
	{ Province_State: 'N/A', Country_Region: 'Burkina Faso' },
	{ Province_State: 'N/A', Country_Region: 'Burma' },
	{ Province_State: 'N/A', Country_Region: 'Burundi' },
	{ Province_State: 'N/A', Country_Region: 'Cabo Verde' },
	{ Province_State: 'N/A', Country_Region: 'Cambodia' },
	{ Province_State: 'N/A', Country_Region: 'Cameroon' },
	{ Province_State: 'N/A', Country_Region: 'Central African Republic' },
	{ Province_State: 'N/A', Country_Region: 'Chad' },
	{ Province_State: 'N/A', Country_Region: 'Chile' },
	{ Province_State: 'N/A', Country_Region: 'Colombia' },
	{ Province_State: 'N/A', Country_Region: 'Congo (Brazzaville)' },
	{ Province_State: 'N/A', Country_Region: 'Congo (Kinshasa)' },
	{ Province_State: 'N/A', Country_Region: 'Costa Rica' },
	{ Province_State: 'N/A', Country_Region: "Cote d'Ivoire" },
	{ Province_State: 'N/A', Country_Region: 'Croatia' },
	{ Province_State: 'N/A', Country_Region: 'Cuba' },
	{ Province_State: 'N/A', Country_Region: 'Cyprus' },
	{ Province_State: 'N/A', Country_Region: 'Czechia' },
	{ Province_State: 'N/A', Country_Region: 'Denmark' },
	{ Province_State: 'N/A', Country_Region: 'Diamond Princess' },
	{ Province_State: 'N/A', Country_Region: 'Djibouti' },
	{ Province_State: 'N/A', Country_Region: 'Dominica' },
	{ Province_State: 'N/A', Country_Region: 'Dominican Republic' },
	{ Province_State: 'N/A', Country_Region: 'Ecuador' },
	{ Province_State: 'N/A', Country_Region: 'Egypt' },
	{ Province_State: 'N/A', Country_Region: 'El Salvador' },
	{ Province_State: 'N/A', Country_Region: 'Equatorial Guinea' },
	{ Province_State: 'N/A', Country_Region: 'Eritrea' },
	{ Province_State: 'N/A', Country_Region: 'Estonia' },
	{ Province_State: 'N/A', Country_Region: 'Eswatini' },
	{ Province_State: 'N/A', Country_Region: 'Ethiopia' },
	{ Province_State: 'N/A', Country_Region: 'Fiji' },
	{ Province_State: 'N/A', Country_Region: 'Finland' },
	{ Province_State: 'N/A', Country_Region: 'France' },
	{ Province_State: 'N/A', Country_Region: 'Gabon' },
	{ Province_State: 'N/A', Country_Region: 'Gambia' },
	{ Province_State: 'N/A', Country_Region: 'Georgia' },
	{ Province_State: 'N/A', Country_Region: 'Germany' },
	{ Province_State: 'N/A', Country_Region: 'Ghana' },
	{ Province_State: 'N/A', Country_Region: 'Greece' },
	{ Province_State: 'N/A', Country_Region: 'Grenada' },
	{ Province_State: 'N/A', Country_Region: 'Guatemala' },
	{ Province_State: 'N/A', Country_Region: 'Guinea' },
	{ Province_State: 'N/A', Country_Region: 'Guinea-Bissau' },
	{ Province_State: 'N/A', Country_Region: 'Guyana' },
	{ Province_State: 'N/A', Country_Region: 'Haiti' },
	{ Province_State: 'N/A', Country_Region: 'Holy See' },
	{ Province_State: 'N/A', Country_Region: 'Honduras' },
	{ Province_State: 'N/A', Country_Region: 'Hungary' },
	{ Province_State: 'N/A', Country_Region: 'Iceland' },
	{ Province_State: 'N/A', Country_Region: 'India' },
	{ Province_State: 'N/A', Country_Region: 'Indonesia' },
	{ Province_State: 'N/A', Country_Region: 'Iran' },
	{ Province_State: 'N/A', Country_Region: 'Iraq' },
	{ Province_State: 'N/A', Country_Region: 'Ireland' },
	{ Province_State: 'N/A', Country_Region: 'Israel' },
	{ Province_State: 'N/A', Country_Region: 'Italy' },
	{ Province_State: 'N/A', Country_Region: 'Jamaica' },
	{ Province_State: 'N/A', Country_Region: 'Japan' },
	{ Province_State: 'N/A', Country_Region: 'Jordan' },
	{ Province_State: 'N/A', Country_Region: 'Kazakhstan' },
	{ Province_State: 'N/A', Country_Region: 'Kenya' },
	{ Province_State: 'N/A', Country_Region: 'Korea, South' },
	{ Province_State: 'N/A', Country_Region: 'Kosovo' },
	{ Province_State: 'N/A', Country_Region: 'Kuwait' },
	{ Province_State: 'N/A', Country_Region: 'Kyrgyzstan' },
	{ Province_State: 'N/A', Country_Region: 'Laos' },
	{ Province_State: 'N/A', Country_Region: 'Latvia' },
	{ Province_State: 'N/A', Country_Region: 'Lebanon' },
	{ Province_State: 'N/A', Country_Region: 'Liberia' },
	{ Province_State: 'N/A', Country_Region: 'Libya' },
	{ Province_State: 'N/A', Country_Region: 'Liechtenstein' },
	{ Province_State: 'N/A', Country_Region: 'Lithuania' },
	{ Province_State: 'N/A', Country_Region: 'Luxembourg' },
	{ Province_State: 'N/A', Country_Region: 'MS Zaandam' },
	{ Province_State: 'N/A', Country_Region: 'Madagascar' },
	{ Province_State: 'N/A', Country_Region: 'Malawi' },
	{ Province_State: 'N/A', Country_Region: 'Malaysia' },
	{ Province_State: 'N/A', Country_Region: 'Maldives' },
	{ Province_State: 'N/A', Country_Region: 'Mali' },
	{ Province_State: 'N/A', Country_Region: 'Malta' },
	{ Province_State: 'N/A', Country_Region: 'Mauritania' },
	{ Province_State: 'N/A', Country_Region: 'Mauritius' },
]
